server:
  port: 8081
eureka:
  client:
    service-url:
#      defaultZone: http://localhost:8082/eureka/,http://localhost:8083/eureka/
      defaultZone: http://localhost:1111/eureka/
spring:
  application:
    name: eureka-client
