spring:
  application:
    name: eureka-server
server:
  port: 8082
eureka:
  instance:
    hostname: peer1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://192.168.0.105:8083/eureka

