spring:
  application:
    name: eureka-server
server:
  port: 1112
eureka:
  instance:
    hostname: peer2
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka

